const char* setup_page = "<html>"
                         "<head>"
                         "<meta charset='utf-8'/>"
                         "<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0'/>"
                         "<title>SAUNA Config</title>"
                         "<style>"
                         "body { background:#000; color:#FFF;} \n"
                         "fieldset {margin:5px; }\n"
                         "label {min-width:150px; display:inline-block;}\n"
                         "input, select {border:solid 1px #CCC; margin:2px; background:#222; display:inline-block; max-width:400px; width:100%; color:#CCC;}\n"
                         "a {color:#FFF;}\n"
                         "</style>"
                         "<script>"
                         "function checkVals() {"
                         "var txt = '';"
                         "var ins = document.getElementsByTagName('input');"
                         "for(var i = 0; i < ins.length; i++) {"
                         "if(ins[i].value != '' && ins[i].hasAttribute('numeric')) {"
                         "if(!/^\\d+$/.test(ins[i].value)) {"
                         "txt += ins[i].name + ' Must be numeric!\\n';"
                         "}"
                         "}"
                         "else if(ins[i].value == '' && !ins[i].hasAttribute('skip')) {"
                         "txt += ins[i].name + ' Must be defined!\\n';"
                         "}"
                         "}"
                         "if(txt != '') {"
                         "alert(txt);"
                         "return false;"
                         "}"
                         "else {"
                         "return true;"
                         "}"
                         "}"
                         "function setSsid(obj) {"
                         "document.getElementById('ap_ssid').value = obj.id;"
                         "return false;"
                         "}"
                         "function enableAdvanced(obj) {"
                         "if(obj.checked && confirm('You are enabling settings that are not regulation and could cause risk of fire or death!!!\\nAre you sure?')) {"
                         "document.getElementById('maxtemp').disabled = false;"
                         "document.getElementById('maxtime').disabled = false;"
                         "document.getElementById('delayoff').disabled = false;"
                         "}"
                         "else {"
                         "document.getElementById('maxtemp').disabled = true;"
                         "document.getElementById('maxtime').disabled = true;"
                         "document.getElementById('delayoff').disabled = true;"
                         "}"
                         "}"
                         "</script>"
                         "</head>"
                         "<body>"
                         "<h1>Sauna Config page</h1>"
                         "Available Access Points<br/>"
                         " AP_LIST <hr/>"
                         "Enter credentials<br/>"
                         "<form action='/save' method='POST' onsubmit='return checkVals()'>"
                         "<fieldset>"
                         "<legend>Access Point Configuration:</legend>"
                         "<label>SSID:</label> <input type='text' name='ap_ssid' id='ap_ssid' maxlength='40'/><br/>"
                         "<label>Password:</label> <input type='password' name='ap_pwd' maxlength='10'/><br/>"
                         "<label>ClientName:</label> <input type='input' name='host_name' value='sauna' maxlength='10'/><br/>"
                         "</fieldset>"
                         "<fieldset>"
                         "<legend>MQTT Configuration:</legend>"
                         "<label>Host:</label> <input type='text' name='mqtt_host' value='192.168.1.1' maxlength='40'/><br/>"
                         "<label>Port:</label> <input type='text' name='mqtt_port' value='1883' maxlength='6' numeric=1/><br/>"
                         "<label>UserName:</label> <input type='text' name='mqtt_user' value='' maxlength='10' skip=1/> <label>(leave blank if no user/pass)</label><br/>"
                         "<label>Password:</label> <input type='password' name='mqtt_pwd' value='' maxlength='10' skip=1/> <label>(leave blank if no user/pass)</label><br/>"
                         "<label>Client ID:</label> <input type='text' name='mqtt_id' value='sauna' maxlength='10'/><br/>"
                         "<label>SubTopic:</label> <input type='text' name='mqtt_sub' value='sonoff/sauna' maxlength='40'/><br/>"
                         "<label>PubTopic:</label> <input type='text' name='mqtt_pub' value='sonoff/sauna/set' maxlength='40'/>"
                         "</fieldset>"
                         "<fieldset>"
                         "<legend>Sauna Configuration:</legend>"
                         "Override Regulatory Rules: <input type='checkbox' name='chk' id='chk' onchange='enableAdvanced(this)' style='width:20px' skip=1/><br/>"
                         "<label>Max Temp:</label> <select name='maxtemp' id='maxtemp' disabled='true'>"
                         "<option value='90' selected>90C (US standard)</option>"
                         "<option value='95'>95C</option>"
                         "<option value='100'>100C</option>"
                         "<option value='105'>105C</option>"
                         "<option value='110'>110C (Finnish recommended max)</option>"
                         "<option value='115'>115C</option>"
                         "<option value='120'>120C (Burn in hell option, your fault if you die)</option>"
                         "</select><br/>"
                         "<label>Max RunTime:</label> <select name='maxtime' id='maxtime' disabled='true'>"
                         "<option value='60' selected>1 Hour (US standard)</option>"
                         "<option value='75'>1 Hour 15min</option>"
                         "<option value='90'>1 Hour 30min</option>"
                         "<option value='105'>1 Hour 45min</option>"
                         "<option value='120'>2 Hours (EU limit)</option>"
                         "</select> <label>(this is the time your sauna will auto off)</label><br/>"
                         "<label>Delay Off:</label> <select name='delayoff' id='delayoff' disabled='true'>"
                         "<option value='false' selected>Auto Off starts immediately (no delay)</option>"
                         "<option value='true' >Auto Off starts when temperature has been reached (delayed)</option>"
                         "</select><br/>"
                         "</fieldset>"
                         "<input type='submit' name='submit' value='Save and restart' style='width:150px' skip=1/>"
                         "</form>"
                         "</body>"
                         "</html>";

const char* save_page =  "<head>"
                         "<meta charset='utf-8'/>"
                         "<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0'/>"
                         "<title>SAUNA Config</title>"
                         "<style>"
                         "body { background:#000; color:#FFF;} "
                         "</style>"
                         "</head>"
                         "<body>"
                         "Rebooting and connecting to WiFi network! You should see it listed in on your access point. In order to reconfigure reset device, by holding button for more than 10seconds."
                         "</body>"
                         "</html>";


const char* ssid_link = "<a href='#' id='SSID' onclick='return setSsid(this)'>SSID_DETAIL</a></br>";
